### ISSUE TITLE
Erro no cadastro de usuários

### ISSUE THREAD

**Issue by cb130felix** [cb130felix/FollowEdu#1]
Não tô conseguindo mais cadastrar usuários depois que os campos extras foram adicionados. Vê issaê Arthur. :dancer:  :dancer:  :dancer:

**Comment by arthurflor23** [comment]
Corrigido.

**Comment by cb130felix** [comment]
era o que?

**Comment by arthurflor23** [comment]
O campo de validação do input de 'Ingresso' que eu tinha preenchido. Aí tirei e pegou.

**Comment by cb130felix** [comment]
Upa o sql do banco com alterações
